SELECT
    ED.ID AS 'ID',
    IFNULL(CD.CHILD_COUNT, 0) AS 'CHILD_COUNT'
FROM ECOLI_DATA ED
LEFT JOIN (
    SELECT
        PARENT_ID,
        COUNT(ID) AS 'CHILD_COUNT'
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) CD ON ED.ID = CD.PARENT_ID
ORDER BY ID;