SELECT 
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM (
    SELECT
        FOOD_TYPE,
        REST_ID,
        REST_NAME,
        FAVORITES,
        MAX(FAVORITES) OVER (PARTITION BY FOOD_TYPE) AS "MAXFAV"
    FROM REST_INFO 
) AS R
WHERE FAVORITES = MAXFAV
ORDER BY FOOD_TYPE DESC;