SELECT SUM(HG.SCORE) AS "SCORE", 
    HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
GROUP BY HE.EMP_NO
HAVING SCORE = (
    SELECT SUM(SCORE)
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC LIMIT 1
);